spring.application.name=car-rental

spring.datasource.url = jdbc:postgresql://ep-ancient-sea-a472bw2n-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username= neondb_owner
spring.datasource.password= ${NEONDB_PASSWORD}
spring.datasource.driver-class-name= org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

application.mail.from=${MAIL_FROM:navamsharma142@gmail.com}
application.mail.verification-url=${APP_VERIFICATION_URL:http://localhost:8080/api/auth/verify-email}
application.mail.verification-token-expiration-minutes=${VERIFICATION_TOKEN_EXP_MINUTES:30}

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG
logging.level.com.sun.mail=DEBUG
spring.mail.properties.mail.debug=true


cloudinary.cloud-name=${CLOUDINARY_USERNAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}